/**
 * @file pmm_small_embedded_static_heap.h
 * @brief PMM preset: SmallEmbeddedStaticHeap — NoLock + StaticStorage/16B granule/16-bit index
 * (SmallEmbeddedStaticConfig)
 *
 * Thin single-header preset file for the PersistMemoryManager library
 * (https://github.com/netkeep80/PersistMemoryManager).
 *
 * Includes the full PMM library (pmm.h) and defines the SmallEmbeddedStaticHeap
 * preset alias in pmm::presets for convenience.
 *
 * Usage:
 * @code
 *   #include "pmm_small_embedded_static_heap.h"
 *
 *   pmm::presets::SmallEmbeddedStaticHeap::create(64 * 1024);
 *   void* ptr = pmm::presets::SmallEmbeddedStaticHeap::allocate(256);
 *   pmm::presets::SmallEmbeddedStaticHeap::deallocate(ptr);
 *
 *   // Persistence (save/load):
 *   pmm::save_manager<pmm::presets::SmallEmbeddedStaticHeap>("heap.dat");
 *   pmm::load_manager_from_file<pmm::presets::SmallEmbeddedStaticHeap>("heap.dat");
 * @endcode
 *
 * Generated by scripts/generate-single-headers.sh
 */

#pragma once

#include "pmm.h"

namespace pmm
{
namespace presets
{

template <std::size_t BufferSize = 1024>
using SmallEmbeddedStaticHeap = PersistMemoryManager<SmallEmbeddedStaticConfig<BufferSize>, 0>;

} // namespace presets
} // namespace pmm
