#!/usr/bin/env bash
# generate-single-headers.sh - Generate single-header preset files for PMM (Issue #123)
#
# Usage: ./scripts/generate-single-headers.sh [--output-dir DIR]
#
# Generates one self-contained single-header .h file per PMM preset into the
# include/ directory (default). Each output file bundles the entire PMM library
# so users can download a single file and start using the chosen preset.
#
# Prerequisites: quom >= 4.0.0 (pip install quom)
#
# Output files:
#   include/pmm_single_threaded_heap.h  — NoLock + HeapStorage (CacheManagerConfig)
#   include/pmm_multi_threaded_heap.h   — SharedMutexLock + HeapStorage (PersistentDataConfig)
#   include/pmm_embedded_heap.h         — NoLock + HeapStorage, grow 50% (EmbeddedManagerConfig)
#   include/pmm_industrial_db_heap.h    — SharedMutexLock + HeapStorage, grow 100% (IndustrialDBConfig)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INCLUDE_DIR="$REPO_ROOT/include"

OUTPUT_DIR="$INCLUDE_DIR"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# ─── Check prerequisites ──────────────────────────────────────────────────────
if ! command -v quom &>/dev/null; then
    echo "ERROR: quom is not installed. Install it with: pip install quom"
    exit 1
fi

echo "quom version: $(quom --version 2>&1 || true)"
echo "Output directory: $OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# ─── Temporary entry-point directory ─────────────────────────────────────────
TMP_ENTRY_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_ENTRY_DIR"' EXIT

# ─── Helper: generate a single preset entry-point header ─────────────────────
# Usage: make_entry_point <filename> <preset_type> <description>
make_entry_point()
{
    local filename="$1"
    local preset_type="$2"
    local description="$3"
    local output_path="$OUTPUT_DIR/$filename"

    cat > "$TMP_ENTRY_DIR/entry_${preset_type}.h" << EOF
/**
 * @file $filename
 * @brief PMM single-header preset: $preset_type — $description
 *
 * Self-contained single-header file generated from the PersistMemoryManager
 * library (https://github.com/netkeep80/PersistMemoryManager).
 *
 * Drop this file into your project and include it — no other files needed.
 *
 * Usage:
 * @code
 *   #include "$filename"
 *
 *   pmm::presets::${preset_type}::create(64 * 1024);
 *   void* ptr = pmm::presets::${preset_type}::allocate(256);
 *   pmm::presets::${preset_type}::deallocate(ptr);
 *
 *   // Persistence (save/load):
 *   pmm::save_manager<pmm::presets::${preset_type}>("heap.dat");
 *   pmm::load_manager_from_file<pmm::presets::${preset_type}>("heap.dat");
 * @endcode
 *
 * Generated by scripts/generate-single-headers.sh
 */

#pragma once

#include "pmm/pmm_presets.h"
#include "pmm/io.h"
#include "pmm/static_storage.h"
#include "pmm/mmap_storage.h"
#include "pmm/storage_backend.h"
#include "pmm/manager_concept.h"
EOF

    echo "Generating $output_path ..."
    quom "$TMP_ENTRY_DIR/entry_${preset_type}.h" "$output_path" -I "$INCLUDE_DIR"
    local lines
    lines=$(wc -l < "$output_path")
    echo "  Done: $output_path ($lines lines)"
}

# ─── Generate one file per preset ────────────────────────────────────────────
make_entry_point \
    "pmm_single_threaded_heap.h" \
    "SingleThreadedHeap" \
    "NoLock + HeapStorage, grow 25% (CacheManagerConfig)"

make_entry_point \
    "pmm_multi_threaded_heap.h" \
    "MultiThreadedHeap" \
    "SharedMutexLock + HeapStorage, grow 25% (PersistentDataConfig)"

make_entry_point \
    "pmm_embedded_heap.h" \
    "EmbeddedHeap" \
    "NoLock + HeapStorage, grow 50% (EmbeddedManagerConfig)"

make_entry_point \
    "pmm_industrial_db_heap.h" \
    "IndustrialDBHeap" \
    "SharedMutexLock + HeapStorage, grow 100% (IndustrialDBConfig)"

echo ""
echo "All single-header presets generated in $OUTPUT_DIR:"
for f in pmm_single_threaded_heap.h pmm_multi_threaded_heap.h \
          pmm_embedded_heap.h pmm_industrial_db_heap.h; do
    echo "  $OUTPUT_DIR/$f ($(wc -l < "$OUTPUT_DIR/$f") lines)"
done
