#!/usr/bin/env bash
# generate-single-headers.sh - Generate single-header files for PMM (Issue #123, #146, #149)
#
# Usage: ./scripts/generate-single-headers.sh [--output-dir DIR]
#
# Generates:
#   1. pmm.h — the full PMM library without preset specializations.
#      Drop this file into your project and include it to use PMM with any config.
#
#   2. One thin specialization file per preset (includes pmm.h + one preset alias):
#      single_include/pmm/pmm_single_threaded_heap.h  — NoLock + HeapStorage (CacheManagerConfig)
#      single_include/pmm/pmm_multi_threaded_heap.h   — SharedMutexLock + HeapStorage (PersistentDataConfig)
#      single_include/pmm/pmm_embedded_heap.h         — NoLock + HeapStorage, grow 50% (EmbeddedManagerConfig)
#      single_include/pmm/pmm_industrial_db_heap.h    — SharedMutexLock + HeapStorage, grow 100% (IndustrialDBConfig)
#      single_include/pmm/pmm_embedded_static_heap.h       — NoLock + StaticStorage/16B (EmbeddedStaticConfig)
#      single_include/pmm/pmm_small_embedded_static_heap.h — NoLock + StaticStorage/16-bit (SmallEmbeddedStaticConfig)
#      single_include/pmm/pmm_large_db_heap.h              — SharedMutexLock + HeapStorage/64-bit (LargeDBConfig)
#
# Prerequisites: quom >= 4.0.0 (pip install quom)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INCLUDE_DIR="$REPO_ROOT/include"

OUTPUT_DIR="$REPO_ROOT/single_include/pmm"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# ─── Check prerequisites ──────────────────────────────────────────────────────
if ! command -v quom &>/dev/null; then
    echo "ERROR: quom is not installed. Install it with: pip install quom"
    exit 1
fi

echo "quom version: $(quom --version 2>&1 || true)"
echo "Output directory: $OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# ─── Temporary entry-point directory ─────────────────────────────────────────
TMP_ENTRY_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_ENTRY_DIR"' EXIT

# ─── Step 1: Generate pmm.h — the full library without preset specializations ─
PMM_H="$OUTPUT_DIR/pmm.h"
cat > "$TMP_ENTRY_DIR/entry_pmm.h" << 'EOF'
/**
 * @file pmm.h
 * @brief PMM single-header library — full PersistMemoryManager without preset specializations.
 *
 * Self-contained single-header file generated from the PersistMemoryManager
 * library (https://github.com/netkeep80/PersistMemoryManager).
 *
 * Drop this file into your project and include it to use PMM with any configuration.
 * Use any of the ready-made preset files (pmm_single_threaded_heap.h, etc.) to get
 * a specific preset, or define your own using PersistMemoryManager<YourConfig>.
 *
 * Usage:
 * @code
 *   #include "pmm.h"
 *
 *   // Use a built-in config directly:
 *   using MyHeap = pmm::PersistMemoryManager<pmm::CacheManagerConfig>;
 *   MyHeap::create(64 * 1024);
 *   void* ptr = MyHeap::allocate(256);
 *   MyHeap::deallocate(ptr);
 *
 *   // Or define your own config:
 *   struct MyConfig {
 *     using address_traits  = pmm::DefaultAddressTraits;
 *     using storage_backend = pmm::HeapStorage<pmm::DefaultAddressTraits>;
 *     using free_block_tree = pmm::AvlFreeTree<pmm::DefaultAddressTraits>;
 *     using lock_policy     = pmm::config::NoLock;
 *     static constexpr std::size_t granule_size     = 16;
 *     static constexpr std::size_t max_memory_gb    = 64;
 *     static constexpr std::size_t grow_numerator   = 3;
 *     static constexpr std::size_t grow_denominator = 2;
 *   };
 *   using CustomHeap = pmm::PersistMemoryManager<MyConfig>;
 * @endcode
 *
 * Generated by scripts/generate-single-headers.sh
 */

#pragma once

#include "pmm/manager_configs.h"
#include "pmm/persist_memory_manager.h"
#include "pmm/pmap.h"
#include "pmm/pstringview.h"
#include "pmm/io.h"
#include "pmm/static_storage.h"
#include "pmm/mmap_storage.h"
#include "pmm/storage_backend.h"
#include "pmm/manager_concept.h"
EOF

echo "Generating $PMM_H ..."
quom "$TMP_ENTRY_DIR/entry_pmm.h" "$PMM_H" -I "$INCLUDE_DIR"
PMM_H_LINES=$(wc -l < "$PMM_H")
echo "  Done: $PMM_H ($PMM_H_LINES lines)"

# ─── Step 2: Generate thin specialization files that include pmm.h ────────────
# Usage: make_preset <filename> <preset_type> <description> <preset_alias_code>
make_preset()
{
    local filename="$1"
    local preset_type="$2"
    local description="$3"
    local preset_alias="$4"
    local output_path="$OUTPUT_DIR/$filename"

    cat > "$output_path" << EOF
/**
 * @file $filename
 * @brief PMM preset: $preset_type — $description
 *
 * Thin single-header preset file for the PersistMemoryManager library
 * (https://github.com/netkeep80/PersistMemoryManager).
 *
 * Includes the full PMM library (pmm.h) and defines the ${preset_type}
 * preset alias in pmm::presets for convenience.
 *
 * Usage:
 * @code
 *   #include "${filename}"
 *
 *   pmm::presets::${preset_type}::create(64 * 1024);
 *   void* ptr = pmm::presets::${preset_type}::allocate(256);
 *   pmm::presets::${preset_type}::deallocate(ptr);
 *
 *   // Persistence (save/load):
 *   pmm::save_manager<pmm::presets::${preset_type}>("heap.dat");
 *   pmm::load_manager_from_file<pmm::presets::${preset_type}>("heap.dat");
 * @endcode
 *
 * Generated by scripts/generate-single-headers.sh
 */

#pragma once

#include "pmm.h"

namespace pmm
{
namespace presets
{

${preset_alias}

} // namespace presets
} // namespace pmm
EOF

    local lines
    lines=$(wc -l < "$output_path")
    echo "  Done: $output_path ($lines lines)"
}

echo ""
echo "Generating preset specialization files..."

make_preset \
    "pmm_single_threaded_heap.h" \
    "SingleThreadedHeap" \
    "NoLock + HeapStorage, grow 25% (CacheManagerConfig)" \
    "using SingleThreadedHeap = PersistMemoryManager<CacheManagerConfig, 0>;"

make_preset \
    "pmm_multi_threaded_heap.h" \
    "MultiThreadedHeap" \
    "SharedMutexLock + HeapStorage, grow 25% (PersistentDataConfig)" \
    "using MultiThreadedHeap = PersistMemoryManager<PersistentDataConfig, 0>;"

make_preset \
    "pmm_embedded_heap.h" \
    "EmbeddedHeap" \
    "NoLock + HeapStorage, grow 50% (EmbeddedManagerConfig)" \
    "using EmbeddedHeap = PersistMemoryManager<EmbeddedManagerConfig, 0>;"

make_preset \
    "pmm_industrial_db_heap.h" \
    "IndustrialDBHeap" \
    "SharedMutexLock + HeapStorage, grow 100% (IndustrialDBConfig)" \
    "using IndustrialDBHeap = PersistMemoryManager<IndustrialDBConfig, 0>;"

make_preset \
    "pmm_embedded_static_heap.h" \
    "EmbeddedStaticHeap" \
    "NoLock + StaticStorage/16B granule (EmbeddedStaticConfig)" \
    "template <std::size_t BufferSize = 4096>
using EmbeddedStaticHeap = PersistMemoryManager<EmbeddedStaticConfig<BufferSize>, 0>;"

make_preset \
    "pmm_small_embedded_static_heap.h" \
    "SmallEmbeddedStaticHeap" \
    "NoLock + StaticStorage/16B granule/16-bit index (SmallEmbeddedStaticConfig)" \
    "template <std::size_t BufferSize = 1024>
using SmallEmbeddedStaticHeap = PersistMemoryManager<SmallEmbeddedStaticConfig<BufferSize>, 0>;"

make_preset \
    "pmm_large_db_heap.h" \
    "LargeDBHeap" \
    "SharedMutexLock + HeapStorage/64B granule/64-bit index (LargeDBConfig)" \
    "using LargeDBHeap = PersistMemoryManager<LargeDBConfig, 0>;"

echo ""
echo "All files generated in $OUTPUT_DIR:"
echo "  $OUTPUT_DIR/pmm.h ($PMM_H_LINES lines)"
for f in pmm_single_threaded_heap.h pmm_multi_threaded_heap.h \
          pmm_embedded_heap.h pmm_industrial_db_heap.h \
          pmm_embedded_static_heap.h \
          pmm_small_embedded_static_heap.h \
          pmm_large_db_heap.h; do
    echo "  $OUTPUT_DIR/$f ($(wc -l < "$OUTPUT_DIR/$f") lines)"
done
